[build-system]
requires = [
  "setuptools>=42",
  "pyserial",
  "toml",
  "pytest"
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
  "test"
]

[pico.build]
PICO_IMAGE = "pico-crypto-key"

[pico.run]
DEVICE_SERIAL = "/dev/ttyACM0"
PICO_CRYPTO_KEY_PIN = "pico"

