[build-system]
requires = [
  "setuptools>=42",
  "pyserial",
  "toml",
  "pytest"
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
  "test"
]

[pico.build]
MBED_TLS_VERSION = "3.1.0"
PICO_SDK_VERSION = "1.3.0"
PICO_IMAGE = "pico-crypto-key"

[pico.install]
DEST_DEVICE = "/media/az/RPI-RP2/"

[pico.run]
DEST_SERIAL = "/dev/ttyACM0"
PICO_CRYPTO_KEY_PIN = "pico"

