[build-system]
requires = [
  "setuptools>=61",
  "pytest"
]
build-backend = "setuptools.build_meta"

[project]
name = "pico-crypto-key"
version = "1.3.0"
authors = [
  { name="Andrew Smith", email="andrew@friarswood.net" },
]
license = {file = "LICENSE.md"}
description = "Raspberry Pi pico cryptography key and python driver"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: linux",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: C++ :: 20",
    "Programming Language :: C :: 17"
]
dependencies = [
    "pyusb>=1.2.1",
    "typer>=0.12.3"
]

[project.scripts]
picobuild = "pico_crypto_key.build:app"

[project.optional-dependencies]
dev = [
  "pytest>=7.1.3",
  "mypy>=1.5.0",
  "mypy-extensions>=1.0.0",
  "ruff>=0.4.1",
  "pandas",
  "ecdsa>=0.19.0"
]

[project.urls]
"Homepage" = "https://github.com/virgesmith/pico-crypto-key"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
  "test"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.ruff]
line-length = 120

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401", "F403"]
