# Board configurations

[default]
PICO_PLATFORM = "rp2040"
PICO_TOOLCHAIN_PATH = "/usr"
PICO_SDK_PATH = "../../pico-sdk-2.0.0"

[pico]
PICO_BOARD = "pico"

[pico_w]
PICO_BOARD = "pico_w"

[tiny2040]
PICO_BOARD = "pimoroni_tiny2040_2mb"

[pico2]
PICO_BOARD = "pico2"
PICO_PLATFORM = "rp2350-arm-s"
PICO_TOOLCHAIN_PATH = "/opt/arm-gcc-13.2"
# TinyUSB release 0.16 doesnt work, use latest SDK which points to a random commit on main
PICO_SDK_PATH = "../../pico-sdk"

[pico2_riscv]
PICO_BOARD = "pico2"
PICO_PLATFORM = "rp2350-riscv"
PICO_TOOLCHAIN_PATH = "/opt/riscv-gcc-14"
# TinyUSB release 0.16 doesnt work, use latest SDK which points to a random commit on main
PICO_SDK_PATH = "../../pico-sdk"
