# Board configurations

[default]
PICO_PLATFORM = "rp2040"
PICO_TOOLCHAIN_PATH = "/usr"
# use latest SDK (2.1.0) which has tinusb 0.17
PICO_SDK_PATH = "../../pico-sdk"

[pico]
PICO_BOARD = "pico"

[pico_w]
PICO_BOARD = "pico_w"

[tiny2040]
PICO_BOARD = "pimoroni_tiny2040_2mb"

[pico2]
PICO_BOARD = "pico2"
PICO_PLATFORM = "rp2350-arm-s"
PICO_TOOLCHAIN_PATH = "/usr"

[pico2-riscv]
PICO_BOARD = "pico2"
PICO_PLATFORM = "rp2350-riscv"
PICO_TOOLCHAIN_PATH = "/opt/riscv-gcc-15"

[pico2_w]
PICO_BOARD = "pico2_w"
PICO_PLATFORM = "rp2350-arm-s"
PICO_TOOLCHAIN_PATH = "/usr"

[pico2_w-riscv]
PICO_BOARD = "pico2_w"
PICO_PLATFORM = "rp2350-riscv"
PICO_TOOLCHAIN_PATH = "/opt/riscv-gcc-15"

